---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: data/homepage.json
  label: Homepage
- type: document
  path: data/fr/homepage.json
  label: Homepage FR
- type: heading
  label: Settings
- type: document
  path: data/settings.json
  label: Site settings
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
